<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>beatsaber-frame-fixes</AssemblyName>
    <RootNamespace>BeatSaberFrameFixes</RootNamespace>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <PropertyGroup Condition="'$(RuntimeIdentifier)' != ''">
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <PublishTrimmed>true</PublishTrimmed>
    <DebugType>none</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Mono.Cecil" Version="0.11.6" />
    <TrimmerRootAssembly Include="Mono.Cecil" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="BeatSaberFrameFixes.Tests" />
  </ItemGroup>

</Project>
