<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>Unity.RenderPipelines.Core.Runtime</AssemblyName>
    <RootNamespace>UnityEngine.Rendering</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\UnityEngine.CoreModule\UnityEngine.CoreModule.csproj" />
  </ItemGroup>

</Project>
