<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>BeatSaber.Haptics</AssemblyName>
    <RootNamespace>BeatSaber.Haptics</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\UnityEngine.CoreModule\UnityEngine.CoreModule.csproj" />
  </ItemGroup>

</Project>
